### ISSUE TITLE
Can't install any .deb files

### ISSUE THREAD

**Issue by six4m** [TheRemote/Ubuntu-Server-raspi4-unofficial#50]
I found out that i can’t install any program, it always says libc6 =>2.17 is not installed.
If i install libc6 package it says libgcc1 is missing,
I tried xubuntu and kubuntu, updated everything with apt-get update and upgrade, but no success,
Maybe you know a solution?

**Comment by pseudofunizer** [comment]
The extension **.deb** kinda give out a clue on what those files are. Although Ubuntu is a branch off of the Debian tree, by default and in my experience, it doesn't handle .deb files all that well. However, if the .deb file is what you've got, there's plenty of ways and workarounds to install a .deb file if you'd just search "installing .deb packages on ubuntu". I.e. : 

https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt 
https://itsfoss.com/install-deb-files-ubuntu/

However, as word of caution - keep in mind that you're likely trying to shove in stuff that wasn't intended for that Linux distro, and in most cases, for the entire processor architecture (ARM64 vs. x86/x64/AMD64). 

If you can choose between a .deb file and even a source code package to compile from, I would recommend choosing the latter. It shouldn't be that much of a hassle, since the (cross)compilers and other libraries are quite up to date in Ubuntu Server in comparison to i.e. Raspbian.
