### ISSUE TITLE
Unable to check for (not upgrade) the bootloader firmware

### ISSUE THREAD

**Issue by freewill404** [TheRemote/Ubuntu-Server-raspi4-unofficial#71]
> sudo apt update
..
> sudo apt upgrade
..
> sudo apt install rpi-eeprom
..
E: Unable to locate package rpi-eeprom

**Comment by TheRemote** [comment]
Ahh yes the new bootloader firmware utility.

This utility is only available on Raspbian at the moment.  I think mostly nobody dares to risk bricking everyone's Pis because if you look at the source code at https://github.com/raspberrypi/rpi-eeprom it makes extensive use of the /opt/vc tools (some of which are not open source).  The 64 bit build of these tools is known to be partially incomplete and poorly tested.  I build the absolute latest vc tools in this image but I wouldn't trust them to perform this update correctly.

Right now no distro has dared to include this utility and I definitely wouldn't be the first because I would never put all of your Pis at risk like that.  If something goes wrong when using this utility you can brick the Pi.

I have written extensively about this utility here: https://jamesachambers.com/raspberry-pi-4-bootloader-firmware-updating-recovery-guide/

The most important thing to understand is that the rpi-eeprom bootloader updates are permanent.  Reformatting your SD card won't affect them as they are actually flashed onto a special EEPROM chip inside the Pi.  This means that if you have a spare SD card or just install Raspbian and then install the bootloader updates you can install anything you want after that.

I actually keep a spare SD card with Raspbian on it just to safely flash these updates.
