### ISSUE TITLE
RTL 8812AU (Kernel issues) 

### ISSUE THREAD

**Issue by UmithanGoktolga** [TheRemote/Ubuntu-Server-raspi4-unofficial#91]
Hi all

I am facing issues while installing the driver for EDIMAX AC600 USB adapter.

Following is my terminal output;

git clone https://github.com/gnab/rtl8812au.git
Cloning into 'rtl8812au'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 749 (delta 15), reused 18 (delta 5), pack-reused 707
Receiving objects: 100% (749/749), 1.96 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (317/317), done.
ubuntu@uav2:~/Desktop$ sudo cp -r rtl8812au  /usr/src/rtl8812au-4.2.2
ubuntu@uav2:~/Desktop$ sudo dkms add -m rtl8812au -v 4.2.2

Creating symlink /var/lib/dkms/rtl8812au/4.2.2/source ->
                 /usr/src/rtl8812au-4.2.2

DKMS: add completed.
ubuntu@uav2:~/Desktop$ sudo dkms build -m rtl8812au -v 4.2.2
Error! Your kernel headers for kernel 4.19.73-v8+ cannot be found.
Please install the linux-headers-4.19.73-v8+ package,
or use the --kernelsourcedir option to tell DKMS where it's located

There is something wrong with kernel headers Is there a way to fix this ..

Thanks a lot ..

**Comment by TheRemote** [comment]
The kernel headers message is a little strange, do you have the headers in /usr/src?  If not you can run the updater in the /home folder to download the latest ones.

Either way, it won't work, because the driver you're trying to build isn't compatible with this new of a kernel.  Check out these links from Google: 

https://askubuntu.com/questions/1046298/dkms-build-issue-with-kernel-4-15-0-20-generic
https://ubuntuforums.org/showthread.php?t=2397202

This is a very common problem and it looks like there's dozens (or more) forks to try to get this driver to keep compiling.

You can verify the kernel headers are working by doing the following:
sudo add-apt-repository ppa:ubuntu-raspi2/ppa -yn
sudo apt update
sudo apt install hello-dkms
